services:

# Satori service
  satori:
    build: .
    container_name: satori
    restart: always
#    cpu_count: 1
#    cpus: 0.75
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
    image: "ghcr.io/telekom-security/satori:24.04.1"
    read_only: true
    volumes:
     - $HOME/tpotce/data/satori/log:/var/log/satori
