networks:
  cowrie_local: null
  dionaea_local: null
  elasticpot_local: null
  sentrypeer_local: null
  tanner_local: null
  nginx_local: null
services:
  tpotinit:
    container_name: tpotinit
    env_file:
    - .env
    restart: always
    stop_grace_period: 60s
    tmpfs:
    - /tmp/etc:uid=2000,gid=2000
    - /tmp/:uid=2000,gid=2000
    network_mode: host
    cap_add:
    - NET_ADMIN
    image: ${TPOT_REPO}/tpotinit:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    volumes:
    - ${TPOT_DOCKER_COMPOSE}:/tmp/tpot/docker-compose.yml:ro
    - ${TPOT_DATA_PATH}/blackhole:/etc/blackhole
    - ${TPOT_DATA_PATH}:/data
    - /var/run/docker.sock:/var/run/docker.sock:ro
  cowrie:
    container_name: cowrie
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    tmpfs:
    - /tmp/cowrie:uid=2000,gid=2000
    - /tmp/cowrie/data:uid=2000,gid=2000
    networks:
    - cowrie_local
    ports:
    - '22:22'
    - '23:23'
    image: ${TPOT_REPO}/cowrie:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    read_only: true
    volumes:
    - ${TPOT_DATA_PATH}/cowrie/downloads:/home/cowrie/cowrie/dl
    - ${TPOT_DATA_PATH}/cowrie/keys:/home/cowrie/cowrie/etc
    - ${TPOT_DATA_PATH}/cowrie/log:/home/cowrie/cowrie/log
    - ${TPOT_DATA_PATH}/cowrie/log/tty:/home/cowrie/cowrie/log/tty
  dionaea:
    container_name: dionaea
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    networks:
    - dionaea_local
    ports:
    - '20:20'
    - '21:21'
    - '42:42'
    - 69:69/udp
    - 81:81
    - 135:135
    - 445:445
    - 1433:1433
    - 1723:1723
    - 1883:1883
    - 3306:3306
    - 27017:27017
    image: ${TPOT_REPO}/dionaea:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    read_only: true
    volumes:
    - ${TPOT_DATA_PATH}/dionaea/roots/ftp:/opt/dionaea/var/dionaea/roots/ftp
    - ${TPOT_DATA_PATH}/dionaea/roots/tftp:/opt/dionaea/var/dionaea/roots/tftp
    - ${TPOT_DATA_PATH}/dionaea/roots/www:/opt/dionaea/var/dionaea/roots/www
    - ${TPOT_DATA_PATH}/dionaea/roots/upnp:/opt/dionaea/var/dionaea/roots/upnp
    - ${TPOT_DATA_PATH}/dionaea:/opt/dionaea/var/dionaea
    - ${TPOT_DATA_PATH}/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
    - ${TPOT_DATA_PATH}/dionaea/log:/opt/dionaea/var/log
    - ${TPOT_DATA_PATH}/dionaea/rtp:/opt/dionaea/var/dionaea/rtp
  elasticpot:
    container_name: elasticpot
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    networks:
    - elasticpot_local
    ports:
    - 9200:9200
    image: ${TPOT_REPO}/elasticpot:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    read_only: true
    volumes:
    - ${TPOT_DATA_PATH}/elasticpot/log:/opt/elasticpot/log
  sentrypeer:
    container_name: sentrypeer
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    networks:
    - sentrypeer_local
    ports:
    - 5060:5060/tcp
    - 5060:5060/udp
    image: ${TPOT_REPO}/sentrypeer:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    read_only: true
    volumes:
    - ${TPOT_DATA_PATH}/sentrypeer/log:/var/log/sentrypeer
  tanner_redis:
    container_name: tanner_redis
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    tty: true
    networks:
    - tanner_local
    image: ${TPOT_REPO}/redis:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    read_only: true
  tanner_phpox:
    container_name: tanner_phpox
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    tty: true
    networks:
    - tanner_local
    image: ${TPOT_REPO}/phpox:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    read_only: true
  tanner_api:
    container_name: tanner_api
    restart: always
    depends_on:
    - tanner_redis
    tmpfs:
    - /tmp/tanner:uid=2000,gid=2000
    tty: true
    networks:
    - tanner_local
    image: ${TPOT_REPO}/tanner:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    read_only: true
    volumes:
    - ${TPOT_DATA_PATH}/tanner/log:/var/log/tanner
    command: tannerapi
  tanner:
    container_name: tanner
    restart: always
    depends_on:
    - tanner_api
    - tanner_phpox
    tmpfs:
    - /tmp/tanner:uid=2000,gid=2000
    tty: true
    networks:
    - tanner_local
    image: ${TPOT_REPO}/tanner:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    command: tanner
    read_only: true
    volumes:
    - ${TPOT_DATA_PATH}/tanner/log:/var/log/tanner
    - ${TPOT_DATA_PATH}/tanner/files:/opt/tanner/files
  snare:
    container_name: snare
    restart: always
    depends_on:
    - tanner
    tty: true
    networks:
    - tanner_local
    ports:
    - 80:80
    image: ${TPOT_REPO}/snare:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
  suricata:
    container_name: suricata
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    environment:
    - OINKCODE=${OINKCODE:-OPEN}
    network_mode: host
    cap_add:
    - NET_ADMIN
    - SYS_NICE
    - NET_RAW
    image: ${TPOT_REPO}/suricata:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    volumes:
    - ${TPOT_DATA_PATH}/suricata/log:/var/log/suricata
