[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning:ldap3.*
    ignore:TripleDES has been moved:cryptography.utils.CryptographyDeprecationWarning
