#!/usr/bin/env python3
"""Write the T-Pot 'conf' fields of docker/p0f/p0f.fp.

  conf = <family>:<share>:<samples>

follows an OS label in [tcp:request] and holds the share of the label's OS family
(Android, Apple = iOS + macOS, Linux, Windows) among the dataset flows p0f gives that
label, and the number of flows. Labels without enough data (and BSD / Other, which
the datasets do not know) get the family alone, 'conf = <family>'; labels whose own
family has less than --min-share of their flows get no conf field. p0f writes it to
the JSON log of client SYNs as os_family / os_confidence / os_samples (exact matches
only, fuzzy matches and the short form get the family alone; userland tools get
os_family Scanner).

Data (both CC BY 4.0, cite when publishing results):
  - CESNET 2024: M. Hulak, V. Bartos, T. Cejka, "Transferability of TCP/IP-based OS
    fingerprinting models", IFIP Networking 2025, https://doi.org/10.5281/zenodo.14703490
    (OS_datasets_0924.zip: subnet1-4.csv, local.csv)
  - MUNI 2021: M. Lastovicka et al., "Passive operating system fingerprinting revisited:
    Evaluation and current challenges", Computer Networks 229 (2023),
    https://doi.org/10.5281/zenodo.7635138 (flows_ground_truth_merged_anonymized.csv)

The datasets hold window, MSS, TTL, SYN size and source port, but not the TCP option
order. Each key (window or mss*N, TTL rounded up to 32/64/128/255, SYN size, port
class) becomes one synthetic SYN with the default option layout and window scale of
the key's majority family; the real p0f reads them with -r. So all flows of a key go
to the label of the majority layout, minority flows count against that label.

Usage (needs Docker and a p0f image built from this tree, docker compose build in
docker/p0f: p0f.fp holds T-Pot fields like ua_family that older images refuse; the
conf lines themselves are stripped before p0f reads the file):
  build_os_confidence.py --cesnet DIR --muni FILE [--fp PATH] [--image IMG] [--min-samples 20] [--min-share 0.5]
"""
import argparse
import collections
import csv
import ipaddress
import json
import os
import random
import re
import struct
import subprocess
import sys
import tempfile

FAMILIES = {"android": "Android", "apple": "Apple", "linux": "Linux", "windows": "Windows", "bsd": "BSD", "other": "Other"}
DATA_FAMILIES = ("android", "apple", "linux", "windows")  # the classes the datasets know
MUNI_FAMILY = {"Windows": "windows", "Android": "android", "iOS": "apple", "Mac OS X": "apple",
               "Linux": "linux", "Ubuntu": "linux", "Fedora": "linux", "Linux Mint": "linux",
               "Slackware": "linux", "Chrome OS": "linux"}
# default SYN option layouts per family and option length in bytes
LAYOUTS = {
    "windows": {12: "mss,nop,ws,nop,nop,sok", 8: "mss,nop,ws", 20: "mss,nop,ws,sok,ts", 4: "mss"},
    "linux": {20: "mss,sok,ts,nop,ws", 12: "mss,nop,nop,sok,nop,ws", 16: "mss,sok,ts", 8: "mss,nop,ws", 4: "mss"},
    "android": {20: "mss,sok,ts,nop,ws", 12: "mss,nop,nop,sok,nop,ws", 16: "mss,sok,ts", 4: "mss"},
    "apple": {24: "mss,nop,ws,nop,nop,ts,sok,eol+1", 20: "mss,nop,ws,nop,nop,ts", 12: "mss,nop,ws,nop,nop,sok", 4: "mss"},
}
DEFAULT_WS = {"windows": 8, "linux": 7, "android": 8, "apple": 6}
SPORT = {"lin": 40000, "hi": 55000, "lo": 20000}
HEADER = """; T-Pot conf fields (begin), generated by docker/p0f/tools/build_os_confidence.py, do not edit.
;   conf = <family>[:<share>:<samples>] after an OS label in [tcp:request]: share of the
;   label's OS family among the dataset flows p0f gives that label (synthetic replay,
;   option layout of the majority family per key), at least {min} flows and a share
;   of {share}; without share: no data, family from the label name. Data (CC BY 4.0):
;   CESNET 2024, Hulak, Bartos, Cejka, IFIP Networking 2025, doi:10.5281/zenodo.14703490
;   MUNI 2021, Lastovicka et al., Computer Networks 229 (2023), doi:10.5281/zenodo.7635138
; T-Pot conf fields (end)
"""


def ttl_bucket(ttl):
    return next((b for b in (32, 64, 128) if ttl <= b), 255)


def window_key(win, mss):
    return f"mss*{win // mss}" if mss and win % mss == 0 and win // mss > 1 else str(win)


def port_class(port):
    return "hi" if port >= 49152 else ("lin" if port >= 32768 else "lo")


def read_cesnet(directory, counts):
    for name in ("subnet1", "subnet2", "subnet3", "subnet4", "local"):
        with open(os.path.join(directory, f"{name}.csv"), newline="") as fh:
            r = csv.reader(fh)
            i = {c: n for n, c in enumerate(next(r))}
            for row in r:
                try:
                    if row[i["PROTOCOL"]] != "6" or row[i["TCP_SYN_SIZE"]] in ("0", "") or row[i["TCP_WIN"]] in ("0", ""):
                        continue
                    fam = "apple" if row[i["OS_LABEL"]] in ("ios", "macos") else row[i["OS_LABEL"]]
                    if fam not in DATA_FAMILIES:
                        continue
                    k = (window_key(int(float(row[i["TCP_WIN"]])), int(float(row[i["TCP_MSS"]] or 0))),
                         ttl_bucket(int(float(row[i["TTL"]]))), int(float(row[i["TCP_SYN_SIZE"]])),
                         port_class(int(float(row[i["SRC_PORT"]]))))
                except (ValueError, KeyError, IndexError):
                    continue
                counts[k][fam] += 1
        print(f"CESNET {name}: {len(counts)} keys so far", file=sys.stderr)


def read_muni(path, counts, wscale):
    with open(path, newline="") as fh:
        r = csv.reader(fh, delimiter=";")
        h = next(r)
        i = {c: n for n, c in enumerate(h)}
        for row in r:
            if len(row) != len(h):
                continue
            try:
                win, ttl = int(row[i["TCP Win Size"]]), int(row[i["TCP SYN TTL"]])
                mss = int(row[i["tcpOptionMaximumSegmentSizeforward"]] or 0)
                k = (window_key(win, mss), ttl_bucket(ttl), int(row[i["TCP SYN Size"]]), port_class(int(row[i["SRC port"]])))
                if row[i["tcpOptionWindowScaleforward"]]:
                    wscale[k[:3]][int(row[i["tcpOptionWindowScaleforward"]])] += 1
            except ValueError:
                continue
            fam = MUNI_FAMILY.get(row[i["UA OS family"]])
            if fam:
                counts[k][fam] += 1
    print(f"MUNI 2021: {len(counts)} keys so far", file=sys.stderr)


def options(layout, mss, ws):
    out = b""
    for o in layout.split(","):
        if o == "mss":
            out += struct.pack("!BBH", 2, 4, mss)
        elif o == "nop":
            out += b"\x01"
        elif o == "ws":
            out += struct.pack("!BBB", 3, 3, ws)
        elif o == "sok":
            out += b"\x04\x02"
        elif o == "ts":
            out += struct.pack("!BBII", 8, 10, random.randint(1, 2**32 - 1), 0)
        elif o.startswith("eol+"):
            out += b"\x00" * (1 + int(o[4:]))
    return out


def csum(data):
    s = sum(struct.unpack(f"!{len(data) // 2}H", data))
    s = (s >> 16) + (s & 0xFFFF)
    return ~(s + (s >> 16)) & 0xFFFF


def syn(idx, v6, ttl, win, opts, sport):
    """Ethernet frame with one SYN from 10.0.0.0 + idx (IPv4) or fd00:: + idx (IPv6)."""
    tcp = struct.pack("!HHIIBBHHH", sport, 443, random.randint(1, 2**32 - 1), 0, (20 + len(opts)) // 4 << 4, 0x02, win, 0, 0) + opts
    if v6:
        ip = (struct.pack("!IHBB", (6 << 28) | random.randint(1, 0xFFFFF), len(tcp), 6, ttl)
              + ipaddress.IPv6Address(int(ipaddress.IPv6Address("fd00::")) + idx).packed + ipaddress.IPv6Address("2001:db8::1").packed)
        return b"\x02\x00\x00\x00\x00\x01\x02\x00\x00\x00\x00\x02\x86\xdd" + ip + tcp
    hdr = struct.pack("!BBHHHBBH4s4s", 0x45, 0, 20 + len(tcp), random.randint(1, 0xFFFF), 0x4000, ttl, 6, 0,
                      ipaddress.IPv4Address(0x0A000000 + idx).packed, ipaddress.IPv4Address("192.0.2.1").packed)
    hdr = hdr[:10] + struct.pack("!H", csum(hdr)) + hdr[12:]
    return b"\x02\x00\x00\x00\x00\x01\x02\x00\x00\x00\x00\x02\x08\x00" + hdr + tcp


def build_packets(counts, wscale):
    """One SYN per key, layout and window scale of the key's majority family."""
    random.seed(7)
    pkts, keys, skipped = [], [], 0
    for k, c in counts.items():
        fam = max(c, key=c.get)
        w, ttl, size, sp = k
        for v6, iph in ((False, 20), (True, 40)):
            layout = LAYOUTS[fam].get(size - iph - 20)
            if layout is None:
                continue
            if w.startswith("mss*"):
                mss = min(1440 if v6 else 1460, 65535 // int(w[4:]))
                win = mss * int(w[4:])
            else:
                mss, win = (1440 if v6 else 1460), int(w)
            if win > 65535:
                continue
            ws = wscale[k[:3]].most_common(1)[0][0] if wscale.get(k[:3]) else DEFAULT_WS[fam]
            keys.append(k)
            pkts.append(syn(len(keys), v6, max(ttl - 8, 1), win, options(layout, mss, ws), SPORT[sp]))
            break
        else:
            skipped += sum(c.values())
    return pkts, keys, skipped


def run_p0f(image, fp_text, pkts):
    with tempfile.TemporaryDirectory() as d:
        with open(os.path.join(d, "p0f.fp"), "w") as fh:
            fh.write(fp_text)
        with open(os.path.join(d, "syn.pcap"), "wb") as fh:
            fh.write(struct.pack("<IHHiIII", 0xA1B2C3D4, 2, 4, 0, 0, 65535, 1))
            for n, p in enumerate(pkts):
                fh.write(struct.pack("<IIII", 1700000000 + n, 0, len(p), len(p)) + p)
        os.chmod(d, 0o755)
        for name in ("p0f.fp", "syn.pcap"):
            os.chmod(os.path.join(d, name), 0o644)
        # -o - writes the JSON log to stdout; a file written by p0f in the container
        # would belong to its user and could not be read back on native Linux Docker
        try:
            out = subprocess.run(["docker", "run", "--rm", "--network", "none", "-v", f"{d}:/work:ro", "--entrypoint",
                                  "/opt/p0f/p0f", image, "-f", "/work/p0f.fp", "-r", "/work/syn.pcap", "-j", "-o", "-"],
                                 check=True, capture_output=True, text=True).stdout
        except subprocess.CalledProcessError as err:
            reason = next((l.strip() for l in err.stderr.splitlines() if "ABORT" in l or "ERROR" in l), err.stderr.strip()[-300:])
            sys.exit(f"p0f in {image} failed: {reason}\n"
                     f"Build the image from this tree first (cd docker/p0f && docker compose build) or pass --image.")
        res = {}
        for line in out.splitlines():
            e = json.loads(line)
            if e.get("mod") != "syn" or not e.get("os") or "fuzzy" in (e.get("params") or ""):
                continue
            ip = ipaddress.ip_address(e["client_ip"])
            res[int(ip) - (0x0A000000 if ip.version == 4 else int(ipaddress.IPv6Address("fd00::")))] = e["os"]
        return res


def label_family(name, flavor):
    """OS family of a p0f label; None for tools and crawlers of unknown OS."""
    if "android" in f"{name} {flavor}".lower():
        return "android"
    n = name.lower()
    if n.startswith("windows"):
        return "windows"
    if n in ("mac os x", "macos x", "ios"):
        return "apple"
    if n == "linux":
        return "linux"
    if n in ("freebsd", "openbsd", "netbsd"):
        return "bsd"
    if n in ("solaris", "openvms", "nextstep", "tru64", "blackberry", "nintendo", "hp-ux", "aix"):
        return "other"
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cesnet", required=True, help="directory with subnet1-4.csv and local.csv")
    ap.add_argument("--muni", required=True, help="flows_ground_truth_merged_anonymized.csv")
    ap.add_argument("--fp", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "../p0f.fp"))
    ap.add_argument("--image", default="dtagdevsec/p0f:24.04.2")
    ap.add_argument("--min-samples", type=int, default=20)
    ap.add_argument("--min-share", type=float, default=0.5,
                    help="no conf field (and so no os_family) below this share of the label's family")
    a = ap.parse_args()

    text = open(a.fp).read()
    # drop earlier output: header block and conf lines
    text = re.sub(r"; T-Pot conf fields \(begin\).*?; T-Pot conf fields \(end\)\n\n?", "", text, flags=re.S)
    text = re.sub(r"^conf\s*=.*\n", "", text, flags=re.M)

    counts = collections.defaultdict(collections.Counter)
    wscale = collections.defaultdict(collections.Counter)
    read_cesnet(a.cesnet, counts)
    read_muni(a.muni, counts, wscale)
    pkts, keys, skipped = build_packets(counts, wscale)
    res = run_p0f(a.image, text, pkts)
    total = sum(sum(c.values()) for c in counts.values())
    print(f"{len(pkts)} synthetic SYNs for {total} flows, {skipped / total:.1%} without a default layout, "
          f"p0f labelled {len(res)} exactly", file=sys.stderr)

    per_label = collections.defaultdict(collections.Counter)
    for idx, k in enumerate(keys, 1):
        if idx in res:
            per_label[res[idx]].update(counts[k])

    lines = text.split("\n")
    out, section = [], ""
    written = 0
    for line in lines:
        out.append(line)
        if line.startswith("["):
            section = line.strip()
            if section == "[tcp:request]":
                out[-1:] = HEADER.format(min=a.min_samples, share=a.min_share).split("\n") + [line]
            continue
        m = re.match(r"^label\s*=\s*([sg]):([^:]+):([^:]+):(.*)$", line)
        if section != "[tcp:request]" or not m or m.group(2) == "!":
            continue
        name, flavor = m.group(3), m.group(4)
        fam = label_family(name, flavor)
        c = per_label.get(f"{name} {flavor}".strip() if flavor else name)
        if not fam:
            continue
        # BSD / Other are no dataset class, labels without enough data: family only
        if fam not in DATA_FAMILIES or not c or sum(c.values()) < a.min_samples:
            out.append(f"conf = {FAMILIES[fam]}")
            written += 1
            print(f"  {FAMILIES[fam]:8} family only            {name} {flavor}", file=sys.stderr)
            continue
        n = sum(c.values())
        if c[fam] / n < a.min_share:
            print(f"  skipped  {c[fam] / n:6.1%} n={n:>9}  {name} {flavor}  (majority {max(c, key=c.get)})", file=sys.stderr)
            continue
        out.append(f"conf = {FAMILIES[fam]}:{c[fam] / n:.3f}:{n}")
        written += 1
        top = max(c, key=c.get)
        flag = "" if top == fam else f"  <- majority is {top}, check the label"
        print(f"  {FAMILIES[fam]:8} {c[fam] / n:6.1%} n={n:>9}  {name} {flavor}{flag}", file=sys.stderr)
    with open(a.fp, "w") as fh:
        fh.write("\n".join(out))
    print(f"{written} conf fields written to {os.path.normpath(a.fp)}", file=sys.stderr)


if __name__ == "__main__":
    main()
