# Generated by Django 3.2.7 on 2021-09-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HenoypotInfoHourlyStatisticsAttackIPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.CharField(max_length=45)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HoneyPotServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=65500)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('key', models.CharField(help_text='Enter 0000 to autogenerate key', max_length=64, unique=True)),
                ('last_input', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoneypotInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shard_id', models.CharField(max_length=32)),
                ('src_ip', models.CharField(max_length=45)),
                ('dst_ip', models.CharField(max_length=45)),
                ('ip_rep', models.CharField(max_length=128, null=True)),
                ('protocol', models.CharField(max_length=45, null=True)),
                ('type', models.CharField(max_length=128)),
                ('eventid', models.CharField(max_length=128, null=True)),
                ('event_type', models.CharField(max_length=128, null=True)),
                ('countryISO', models.CharField(max_length=4, null=True)),
                ('event_timestamp', models.DateTimeField()),
                ('recieved_timestamp', models.DateTimeField(auto_now=True)),
                ('raw_entry', models.JSONField()),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CollectorAPI.honeypotserver')),
            ],
            options={
                'unique_together': {('shard_id', 'event_timestamp')},
            },
        ),
    ]
