# Generated by Django 3.2.7 on 2021-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectorAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='honeypotinfo',
            index=models.Index(fields=['event_timestamp'], name='CollectorAP_event_t_38766e_idx'),
        ),
    ]
