# Generated by Django 3.2.7 on 2021-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectorAPI', '0002_honeypotinfo_collectorap_event_t_38766e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypotinfo',
            name='city_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='honeypotinfo',
            name='continent_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='honeypotinfo',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='honeypotinfo',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='honeypotinfo',
            name='region_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='honeypotinfo',
            name='region_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
