# Generated by Django 3.2.7 on 2021-10-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollectorAPI', '0003_auto_20211017_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_entry', models.JSONField()),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CollectorAPI.honeypotinfo')),
            ],
        ),
    ]
