# Generated by Django 3.2.7 on 2021-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectorAPI', '0006_honeypotagregate24hips_honeypotagregate30dips_honeypotagregate7dips'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotAgregate24hCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_iso', models.CharField(max_length=4, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HoneypotAgregate30DCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_iso', models.CharField(max_length=4, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HoneypotAgregate7DCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_iso', models.CharField(max_length=4, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
