# Generated by Django 3.2.7 on 2021-10-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectorAPI', '0007_honeypotagregate24hcountry_honeypotagregate30dcountry_honeypotagregate7dcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotAgregatePerServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=45)),
                ('data', models.JSONField()),
            ],
        ),
    ]
