# Generated by Django 3.2.7 on 2021-11-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectorAPI', '0008_honeypotagregateperserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotReportsStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('affected_honeys', models.JSONField()),
                ('countries', models.JSONField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
