# Generated by Django 3.2.7 on 2021-11-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollectorAPI', '0009_honeypotreportsstorage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='honeypotreportsstorage',
            unique_together={('from_date', 'to_date')},
        ),
    ]
