# Generated by Django 3.2.7 on 2022-03-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollectorAPI', '0010_alter_honeypotreportsstorage_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
            ],
            options={
                'permissions': (('adv_reports', 'Може да създава подробни доклади'), ('graphs', 'Може да изпозлва Graphs'), ('tables', 'Може да използва tables')),
            },
        ),
    ]
