networks:
  beelzebub_local:

services:

# Beelzebub service
  beelzebub:
    build: .
    container_name: beelzebub
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - beelzebub_local
    ports:
      - "22:22"
      - "80:80"
      - "2222:2222"
      - "3306:3306"
      - "8080:8080"
    # Prepared Beelzebub services, uncomment to expose
    #  - "23:23"
    #  - "389:389"
    #  - "445:445"
    #  - "1433:1433"
    #  - "1883:1883"
    #  - "3389:3389"
    #  - "5432:5432"
    #  - "5900:5900"
    #  - "6379:6379"
    #  - "8000:8000"
    #  - "8081:8081"
    #  - "8888:8888"
    #  - "11211:11211"
    environment:
      LLM_PROVIDER: "ollama"
      LLM_MODEL: "llama3.1:8b"
      LLM_HOST: "http://ollama.local:11434/api/chat"
    #  LLM_PROVIDER: "openai"
    #  LLM_MODEL: "gpt-4o"
    #  LLM_HOST: ""
    #  OPEN_AI_SECRET_KEY: "sk-proj-123456"
    image: "ghcr.io/telekom-security/beelzebub:24.04.2"
    read_only: true
    volumes:
     - $HOME/tpotce/data/beelzebub/key:/opt/beelzebub/configurations/key
     - $HOME/tpotce/data/beelzebub/log:/opt/beelzebub/configurations/log
