services:

## Kibana service
  kibana:
    build: .
    container_name: kibana
#    mem_limit: 2g
#    environment:
#      NODE_OPTIONS: "--max-old-space-size=1024"
    restart: always
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
    ports:
     - "127.0.0.1:64296:5601"
    image: "ghcr.io/telekom-security/kibana:24.04.1"
