name: Link Checker

on:
  schedule:
    - cron: '0 2 * * *' # daily at 2 AM UTC
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --verbose README.md
